{{- if and .Values.secret.create .Values.secret.githubToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "starsync.secretName" . }}
  labels:
    {{- include "starsync.labels" . | nindent 4 }}
type: Opaque
stringData:
  STARSYNC_GITHUB_TOKEN: {{ .Values.secret.githubToken | quote }}
{{- end }}
