apiVersion: v1
kind: ConfigMap
metadata:
  name: starsync-config
  namespace: starsync
data:
  STARSYNC_DATA_DIR: /data
  STARSYNC_STATE_DIR: /state
  STARSYNC_SEARCH_INDEX_DIR: /index
  STARSYNC_UI_DIR: /ui
  STARSYNC_BIND: 0.0.0.0:8989
  STARSYNC_STORAGE_BACKEND: local
  STARSYNC_UI_ENABLED: "true"
  STARSYNC_UI_AUTO_EXTRACT: "true"
  RUST_LOG: info
