apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starsync
  namespace: starsync
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: starsync.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: starsync
                port:
                  name: http
