apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: starsync-data
  namespace: starsync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: starsync-state
  namespace: starsync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: starsync-index
  namespace: starsync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
