apiVersion: v1
kind: Service
metadata:
  name: starsync
  namespace: starsync
  labels:
    app.kubernetes.io/name: starsync
    app.kubernetes.io/part-of: starsync
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: starsync
  ports:
    - name: http
      port: 8989
      targetPort: http
